const rawData = [
    // --- DEITIES (The Source) ---
    {id:"Narayana", label:"Nārāyaṇa", group:"Deity", region:"Divine", isDeity:true, note:"The Preserver; source of Vaishnava lineages."},
    {id:"Shiva", label:"Śiva", group:"Deity", region:"Divine", isDeity:true, note:"The Destroyer; Adi Guru of Yoga and Tantra."},
    {id:"Brahma", label:"Brahmā", group:"Deity", region:"Divine", isDeity:true, note:"The Creator."},
    {id:"Shakti", label:"Śakti", group:"Deity", region:"Divine", isDeity:true, note:"Divine Mother; dynamic energy."},
    {id:"Rudra", label:"Rudra", group:"Deity", region:"Divine", isDeity:true, note:"Vedic form of Shiva."},
    {id:"Bhairava", label:"Bhairava", group:"Deity", region:"Divine", isDeity:true, note:"Fierce form of Shiva (Trika source)."},
    {id:"Bhairavi", label:"Bhairavī Devi", group:"Deity", region:"Divine", isDeity:true, note:"Tantric Goddess."},
    {id:"FourKumaras", label:"Four Kumāras", group:"Deity", region:"Divine", isDeity:true, note:"Mind-born sons of Brahma."},
    {id:"Hiranyagarbha", label:"Hiraṇyagarbha", group:"Deity", region:"Divine", isDeity:true, note:"Cosmic Womb; source of Yoga."},
    {id:"Manjushri", label:"Mañjuśrī", group:"Deity", region:"Divine", isDeity:true, note:"Bodhisattva of Wisdom."},
    {id:"Vajradhara", label:"Vajradhara", group:"Deity", region:"Divine", isDeity:true, note:"Primordial Buddha (Tantric)."},

    // --- ANCIENT RISHIS ---
    {id:"Dhanvantari", label:"Dhanvantari", year:-3000, school:"Ayurveda", region:"Vedic", work:"Ayurveda", others:["Dhanvantari Nighantu"], note:"God of Medicine."},
    {id:"Vashishta", label:"Vashishta", year:-3000, school:"Vedas", region:"North", work:"Rig Veda 7", others:["Yoga Vashishta"], note:"Primordial Sage."},
    {id:"Parashara", label:"Parashara", year:-2000, school:"Vedas", region:"North", work:"Vishnu Purana", others:["Parashara Smriti"], note:"Father of Vyasa."},
    {id:"Vyasa", label:"Vyasa", year:-1500, school:"Vedas", region:"North", work:"Mahabharata", others:["Brahma Sutras", "Puranas"], note:"Compiler of Vedas."},
    {id:"Shuka", label:"Shuka", year:-1400, school:"Advaita", region:"North", work:"Bhagavata (Narrator)", others:[], note:"Son of Vyasa."},
    {id:"Yajnavalkya", label:"Yajnavalkya", year:-850, school:"Vedas", region:"East", subregion:"Mithila", work:"Brihadaranyaka", others:["Shatapatha Brahmana"], note:"Greatest Upanishadic sage."},
    {id:"Maitreyi", label:"Maitreyi", year:-850, school:"Vedas", region:"East", subregion:"Mithila", note:"Philosopher wife."},
    {id:"Gargi", label:"Gargi", year:-850, school:"Vedas", region:"East", subregion:"Mithila", note:"Vedic debater."},
    {id:"Kapila", label:"Kapila", year:-600, school:"Samkhya", region:"North", work:"Samkhya Sutras", others:[], note:"Founder of Samkhya."},
    {id:"Asuri", label:"Asuri", year:-580, school:"Samkhya", region:"North", note:"Disciple of Kapila."},
    {id:"Panchashikha", label:"Panchashikha", year:-550, school:"Samkhya", region:"North", note:"Expanded Samkhya."},
    {id:"Jaimini", label:"Jaimini", year:-300, school:"Mimamsa", region:"North", work:"Mimamsa Sutras", others:[], note:"Ritualism."},
    {id:"Gautama", label:"Gautama", year:-200, school:"Nyaya", region:"East", subregion:"Mithila", work:"Nyaya Sutras", others:[], note:"Logic Founder."},
    {id:"Kanada", label:"Kanada", year:-200, school:"Vaisheshika", region:"West", subregion:"Gujarat", work:"Vaisheshika Sutras", others:[], note:"Atomism."},
    {id:"Patanjali", label:"Patanjali", year:-150, school:"Yoga", region:"North", subregion:"Kashmir", work:"Yoga Sutras", others:["Mahabhasya"], note:"Systematized Yoga."},
    {id:"Panini", label:"Panini", year:-500, school:"Grammar", region:"North West", subregion:"Gandhara", work:"Ashtadhyayi", others:["Dhatupatha"], note:"Linguistics."},
    {id:"Chanakya", label:"Chanakya", year:-350, school:"Statecraft", region:"East", subregion:"Magadha", work:"Arthashastra", others:["Chanakya Niti"], note:"Realpolitik."},
    {id:"Sushruta", label:"Sushruta", year:-600, school:"Medicine", region:"North", work:"Sushruta Samhita", others:[], note:"Surgery."},
    
    // --- HETERODOX ---
    {id:"Buddha", label:"Buddha", year:-563, school:"Buddhism", region:"East", subregion:"Magadha", work:"Pali Canon", others:["Dhammapada"], note:"The Awakened One."},
    {id:"Mahavira", label:"Mahavira", year:-540, school:"Jainism", region:"East", subregion:"Bihar", work:"Agamas", others:[], note:"24th Tirthankara."},
    {id:"Makkhali", label:"Makkhali Gosala", year:-500, school:"Ajivika", region:"East", subregion:"Magadha", work:"(Lost)", others:[], note:"Founder of Ajivika."},
    {id:"Charvaka", label:"Charvaka", year:-600, school:"Charvaka", region:"North", work:"Barhaspatya Sutras", others:[], note:"Materialist."},
    {id:"Brihaspati", label:"Brihaspati", year:-700, school:"Charvaka", region:"North", note:"Materialist Founder."},

    // --- MISSING FIGURES (ADDED) ---
    {id:"Nagarjuna", label:"Nāgārjuna", year:150, school:"Buddhism", region:"South", subregion:"Andhra", work:"Mulamadhyamakakarika", others:["Sunyatasaptati"], note:"Madhyamaka Founder."},
    {id:"Aryadeva", label:"Āryadeva", year:200, school:"Buddhism", region:"South", subregion:"Andhra", work:"Catuhsataka", others:[], note:"Disciple of Nagarjuna."},
    {id:"Dignaga", label:"Dignāga", year:480, school:"Buddhism", region:"South", subregion:"Kanchipuram", work:"Pramana-samuccaya", others:[], note:"Buddhist Logic."},
    {id:"Huineng", label:"Huineng", year:638, school:"Buddhism", region:"China", work:"Platform Sutra", others:[], note:"6th Chan Patriarch."},
    {id:"Milarepa", label:"Milarepa", year:1052, school:"Buddhism", region:"Tibet", work:"Hundred Thousand Songs", others:[], note:"Yogi & Poet."},
    {id:"Bhadrabahu", label:"Bhadrabahu", year:-300, school:"Jainism", region:"South", subregion:"Karnataka", work:"Kalpa Sutra", others:[], note:"Spiritual Teacher of Chandragupta."},
    {id:"Kundakunda", label:"Kundakunda", year:100, school:"Jainism", region:"South", work:"Samayasara", others:["Niyamasara"], note:"Digambara Leader."},
    {id:"Kalidasa", label:"Kālidāsa", year:400, school:"Literature", region:"Central", subregion:"Ujjain", work:"Shakuntalam", others:["Meghaduta", "Raghuvamsha"], note:"Greatest Sanskrit Poet."},


    // --- ADVAITA LINEAGE ---
    {id:"Gaudapada", label:"Gaudapada", year:600, school:"Advaita", region:"North", work:"Mandukya Karika", others:[], note:"Grand-guru of Shankara."},
    {id:"Govinda", label:"Govinda Bhagavatpada", year:750, school:"Advaita", region:"Central", work:"Yoga Taravali", others:[], note:"Guru of Shankara."},
    {id:"Shankara", label:"Adi Shankara", year:788, school:"Advaita", region:"South", subregion:"Kerala", work:"Brahmasutra Bhashya",workUrl: "https://www.wisdomlib.org/hinduism/book/brahma-sutras", others:["Vivekachudamani", "Bhaja Govindam"], note:"Systematizer."},
    {id:"Suresvara", label:"Suresvara", year:800, school:"Advaita", region:"South", work:"Naishkarmya Siddhi", others:["Vartikas"], note:"Disciple."},
    {id:"Padmapada", label:"Padmapada", year:800, school:"Advaita", region:"South", work:"Panchapadika", others:[], note:"Disciple."},
    {id:"Hastamalaka", label:"Hastamalakacharya", year:800, school:"Advaita", region:"South", note:"Disciple."},
    {id:"Totaka", label:"Totakacharya", year:800, school:"Advaita", region:"South", work:"Totakashtakam", others:[], note:"Disciple."},
    {id:"Vidyaranya", label:"Vidyaranya", year:1296, school:"Advaita", region:"South", subregion:"Karnataka", work:"Panchadasi", others:["Jivanmuktiviveka"], note:"Vijayanagara Patron."},
    {id:"Madhusudana", label:"Madhusudana Sarasvati", year:1540, school:"Advaita", region:"East", subregion:"Bengal", work:"Advaita Siddhi", others:["Gudhartha Dipika"], note:"Dialectician."},

    // --- DVAITA LINEAGE ---
    {id:"Achyuta", label:"Achyuta Preksha", year:1200, school:"Dvaita", region:"South", subregion:"Udupi", note:"Guru of Madhva."},
    {id:"Madhva", label:"Madhvacharya", year:1238, school:"Dvaita", region:"South", subregion:"Karnataka", work:"Sarvamula", others:["Mahabharata Tatparya Nirnaya"], note:"Founder of Dualism."},
    {id:"Padmanabha", label:"Padmanabha Tirtha", year:1300, school:"Dvaita", region:"South", note:"Disciple."},
    {id:"Narahari", label:"Narahari Tirtha", year:1300, school:"Dvaita", region:"South", note:"Disciple."},
    {id:"Jayatirtha", label:"Jayatirtha", year:1365, school:"Dvaita", region:"South", subregion:"Karnataka", work:"Nyaya Sudha", others:["Vadavali"], note:"Systematizer."},
    {id:"Vyasatirtha", label:"Vyasatirtha", year:1460, school:"Dvaita", region:"South", subregion:"Karnataka", work:"Nyayamrita", others:["Tarkatandava"], note:"Guru of Krishnadevaraya."},
    {id:"Raghavendra", label:"Raghavendra Tirtha", year:1595, school:"Dvaita", region:"South", subregion:"Mantralayam", work:"Parimala", others:[], note:"Saint Scholar."},

    // --- VISHISHTADVAITA ---
    {id:"Nammalvar", label:"Nammalvar", year:880, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Tiruvaymoli", others:[], note:"Alvar."},
    {id:"Nathamuni", label:"Nathamuni", year:900, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Yoga Rahasya", others:["Nyayatattva"], note:"First Acharya."},
    {id:"Yamuna", label:"Yamunacharya", year:917, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Siddhitraya", others:["Gitartha Sangraha"], note:"Preceptor."},
    {id:"Ramanuja", label:"Ramanuja", year:1017, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Sri Bhashya", others:["Vedartha Sangraha"], note:"Founder."},
    {id:"Desika", label:"Vedanta Desika", year:1268, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Paduka Sahasram", others:["Rahasyatrayasara"], note:"Vadakalai Leader."},
    {id:"Pillai", label:"Pillai Lokacharya", year:1205, school:"Vishishtadvaita", region:"South", subregion:"Tamil Nadu", work:"Srivachana Bhushanam", others:[], note:"Thenkalai Leader."},

    // --- KASHMIR SHAIVISM ---
    {id:"Vasugupta", label:"Vasugupta", year:800, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Shiva Sutras", others:["Spanda Karika"], note:"Founder."},
    {id:"Somananda", label:"Somananda", year:900, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Shiva Drishti", others:[], note:"Pratyabhijna."},
    {id:"Utpaladeva", label:"Utpaladeva", year:925, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Ishvara Pratyabhijna", others:["Sivastotravali"], note:"Architect."},
    {id:"Abhinavagupta", label:"Abhinavagupta", year:950, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Tantraloka", others:["Abhinavabharati"], note:"Tantric Genius."},
    {id:"Kshemaraja", label:"Kshemaraja", year:1000, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Pratyabhijnahridayam", others:[], note:"Disciple."},
    {id:"Lakshmanjoo", label:"Lakshmanjoo", year:1907, school:"Kashmir Shaivism", region:"North", subregion:"Kashmir", work:"Secret Supreme", others:[], note:"Modern Master."},

    // --- NYAYA & NAVYA-NYAYA ---
    {id:"Vatsyayana", label:"Vatsyayana", year:450, school:"Nyaya", region:"North", work:"Nyaya Bhashya", others:[], note:"Commentator."},
    {id:"Uddyotakara", label:"Uddyotakara", year:600, school:"Nyaya", region:"North", work:"Nyaya Varttika", others:[], note:"Commentator."},
    {id:"Vacaspati", label:"Vacaspati Mishra", year:900, school:"Nyaya", region:"East", subregion:"Mithila", work:"Nyaya Tatparya Tika", others:["Bhamati"], note:"Polymath."},
    {id:"Udayana", label:"Udayana", year:984, school:"Nyaya", region:"East", subregion:"Mithila", work:"Kusumanjali", others:["Atmatattvaviveka"], note:"Theist Logic."},
    {id:"Gangesa", label:"Gangesa", year:1325, school:"Nyaya", region:"East", subregion:"Mithila", work:"Tattvacintamani", others:[], note:"Navya-Nyaya Founder."},
    {id:"Raghunatha", label:"Raghunatha Shiromani", year:1477, school:"Nyaya", region:"East", subregion:"Bengal", work:"Didhiti", others:[], note:"Logician."},
    {id:"Gadadhara", label:"Gadadhara", year:1650, school:"Nyaya", region:"East", subregion:"Bengal", work:"Shaktivada", others:[], note:"Logician."},

    // --- MIMAMSA ---
    {id:"Shabara", label:"Shabara", year:200, school:"Mimamsa", region:"North", work:"Shabara Bhashya", others:[], note:"Commentator."},
    {id:"Kumarila", label:"Kumarila Bhatta", year:700, school:"Mimamsa", region:"North", subregion:"Prayag", work:"Slokavartika", others:["Tantravartika"], note:"Bhatta School."},
    {id:"Prabhakara", label:"Prabhakara", year:700, school:"Mimamsa", region:"South", subregion:"Kerala", work:"Brihati", others:[], note:"Guru School."},
    {id:"Mandana", label:"Mandana Mishra", year:800, school:"Mimamsa", region:"East", subregion:"Mithila", work:"Brahmasiddhi", others:[], note:"Debater."},

    // --- SAMKHYA & YOGA & VAISHESHIKA ---
    {id:"IshvaraKrishna", label:"Ishvara Krishna", year:350, school:"Samkhya", region:"North", work:"Samkhya Karika", others:[], note:"Classical Samkhya."},
    {id:"Vijnanabhikshu", label:"Vijnanabhikshu", year:1550, school:"Yoga", region:"North", work:"Yogavarttika", others:[], note:"Syncretic."},
    {id:"Prashastapada", label:"Prashastapada", year:550, school:"Vaisheshika", region:"North", work:"Padarthadharmasamgraha", others:[], note:"Atomism."},

    // --- OTHER VEDANTA ---
    {id:"Nimbarka", label:"Nimbarka", year:1150, school:"Dvaitadvaita", region:"South", subregion:"Andhra", work:"Parijata Saurabha", others:["Dasasloki"], note:"Dvaitadvaita."},
    {id:"Vallabha", label:"Vallabhacharya", year:1479, school:"Shuddhadvaita", region:"West", subregion:"Gujarat", work:"Anubhashya", others:["Subodhini"], note:"Pushtimarg."},
    {id:"Srinivasa", label:"Srinivasa Acharya", year:1200, school:"Dvaitadvaita", region:"South", note:"Disciple."},
    {id:"Vitthalanatha", label:"Vitthalanatha", year:1516, school:"Shuddhadvaita", region:"North", subregion:"Braj", note:"Son of Vallabha."},

    // --- BUDDHISM LINEAGE ---
    {id:"Upali", label:"Upali", year:-500, school:"Buddhism", region:"East", subregion:"Magadha", note:"Vinaya Master."},
    {id:"Mahakassapa", label:"Mahakassapa", year:-500, school:"Buddhism", region:"East", note:"1st Patriarch."},
    {id:"Ananda", label:"Ananda", year:-500, school:"Buddhism", region:"East", note:"Dhamma Keeper."},
    {id:"Mahinda", label:"Mahinda", year:-250, school:"Buddhism", region:"South", subregion:"Sri Lanka", note:"Ashoka's Son."},
    {id:"Buddhaghosa", label:"Buddhaghosa", year:430, school:"Buddhism", region:"South", subregion:"Sri Lanka", work:"Visuddhimagga", others:[], note:"Theravada."},
    {id:"Asanga", label:"Asanga", year:350, school:"Buddhism", region:"North West", subregion:"Gandhara", work:"Yogacarabhumi", others:["Mahayana-Samgraha"], note:"Yogacara."},
    {id:"Vasubandhu", label:"Vasubandhu", year:350, school:"Buddhism", region:"North West", subregion:"Gandhara", work:"Abhidharmakosha", others:["Vimsatika"], note:"Yogacara."},
    {id:"Dharmakirti", label:"Dharmakirti", year:600, school:"Buddhism", region:"South", work:"Pramanavarttika", others:["Nyayabindu"], note:"Logic."},
    {id:"Bodhidharma", label:"Bodhidharma", year:480, school:"Buddhism", region:"China", subregion:"Kanchipuram", work:"Zen Teachings", others:[], note:"Zen Founder."},
    {id:"Padmasambhava", label:"Padmasambhava", year:750, school:"Buddhism", region:"Tibet", subregion:"Swat", note:"Guru Rinpoche."},
    {id:"Atisha", label:"Atisha", year:982, school:"Buddhism", region:"Tibet", subregion:"Bengal", note:"Kadampa Founder."},
    {id:"Tsongkhapa", label:"Tsongkhapa", year:1357, school:"Buddhism", region:"Tibet", note:"Gelug Founder."},
    {id:"DalaiLama", label:"Dalai Lama (14th)", year:1935, school:"Buddhism", region:"Tibet", note:"14th.", others:[]},

    // --- JAINISM LINEAGE ---
    {id:"GautamaGanadhara", label:"Gautama Ganadhara", year:-500, school:"Jainism", region:"East", subregion:"Bihar", note:"Disciple."},
    {id:"Sudharma", label:"Sudharma", year:-500, school:"Jainism", region:"East", subregion:"Bihar", note:"Disciple."},
    {id:"Umaswati", label:"Umaswati", year:200, school:"Jainism", region:"West", work:"Tattvartha Sutra", others:[], note:"Shared Text."},
    {id:"Siddhasena", label:"Siddhasena", year:480, school:"Jainism", region:"West", work:"Nyayavatara", others:[], note:"Logician."},
    {id:"Haribhadra", label:"Haribhadra Suri", year:750, school:"Jainism", region:"West", subregion:"Gujarat", work:"Saddarshanasamuccaya", others:[], note:"Philosopher."},
    {id:"Hemachandra", label:"Hemachandra", year:1088, school:"Jainism", region:"West", subregion:"Gujarat", work:"Yogasastra", others:["Siddha-Hema"], note:"Polymath."},

    // --- BHAKTI & LIT ---
    {id:"Vidyapati", label:"Vidyapati", year:1352, school:"Literature", region:"East", subregion:"Mithila", work:"Padavali", others:["Kirtilata"], note:"Maithili Poet."},
    {id:"Jayadeva", label:"Jayadeva", year:1200, school:"Bhakti", region:"East", subregion:"Odisha", work:"Gita Govinda", others:["Dasavatara Stotra"], note:"Poet."},
    {id:"Chaitanya", label:"Chaitanya", year:1486, school:"Bhakti", region:"East", subregion:"Bengal", work:"Siksastakam", others:[], note:"Gaudiya Founder."},
    {id:"Kabir", label:"Kabir", year:1440, school:"Bhakti", region:"North", subregion:"Varanasi", work:"Bijak", others:["Sakhi Granth"], note:"Nirguna."},
    {id:"Tulsidas", label:"Tulsidas", year:1532, school:"Bhakti", region:"North", subregion:"Varanasi", work:"Ramcharitmanas", others:["Vinaya Patrika"], note:"Ramayana."},
    {id:"Surdas", label:"Surdas", year:1478, school:"Bhakti", region:"North", subregion:"Braj", work:"Sur Sagar", others:["Sur Saravali"], note:"Krishna Bhakta."},
    {id:"Mirabai", label:"Mirabai", year:1498, school:"Bhakti", region:"West", subregion:"Rajasthan", work:"Bhajans", others:[], note:"Krishna Bhakta."},
    {id:"Andal", label:"Andal", year:750, school:"Bhakti", region:"South", subregion:"Tamil Nadu", work:"Tiruppavai", others:["Nachiyar Tirumoli"], note:"Alvar."},
    {id:"Appayya", label:"Appayya Dikshita", year:1520, school:"Shaiva", region:"South", subregion:"Tamil Nadu", work:"Siddhantalesa", others:["Kuvalayananda"], note:"Polymath."},
    {id:"Tyagaraja", label:"Tyagaraja", year:1767, school:"Music", region:"South", subregion:"Tamil Nadu", work:"Pancharatna", others:[], note:"Musician."},
    {id:"Muthuswami", label:"Muthuswami Dikshitar", year:1775, school:"Music", region:"South", subregion:"Tamil Nadu", work:"Navagraha Kritis", others:[], note:"Musician."},
    {id:"SyamaSastri", label:"Syama Sastri", year:1762, school:"Music", region:"South", subregion:"Tamil Nadu", work:"Swarajatis", others:[], note:"Musician."},
    {id:"AmirKhusrau", label:"Amir Khusrau", year:1253, school:"Literature", region:"North", subregion:"Delhi", work:"Qiran-us-Sa'dain", others:["Tughlaq Nama"], note:"Poet."},

    // --- MODERN ERA ---
    {id:"RamMohan", label:"Ram Mohan Roy", year:1772, school:"Modern", region:"East", subregion:"Bengal", work:"Brahmo Samaj", others:["Precepts of Jesus"], note:"Reformer."},
    {id:"Bankim", label:"Bankim Chandra", year:1838, school:"Literature", region:"East", subregion:"Bengal", work:"Anandamath", others:["Vande Mataram"], note:"Novelist."},
    {id:"Vivekananda", label:"Vivekananda", year:1863, school:"Advaita", region:"East", subregion:"Bengal", work:"Raja Yoga", others:["Karma Yoga", "Chicago Address"], note:"Global Vedanta."},
    {id:"Tagore", label:"Rabindranath Tagore", year:1861, school:"Literature", region:"East", subregion:"Bengal", work:"Gitanjali", others:["Gora", "Jana Gana Mana"], note:"Nobel Laureate."},
    {id:"Aurobindo", label:"Sri Aurobindo", year:1872, school:"Yoga", region:"East", subregion:"Pondicherry", work:"Life Divine", others:["Savitri"], note:"Integral Yoga."},
    {id:"Ramanujan", label:"Srinivasa Ramanujan", year:1887, school:"Science", region:"South", subregion:"Tamil Nadu", work:"Notebooks", others:["Mock Theta Functions"], note:"Math Genius."},
    {id:"Ambedkar", label:"B.R. Ambedkar", year:1891, school:"Modern", region:"West", subregion:"Maharashtra", work:"Constitution", others:["Annihilation of Caste"], note:"Social Justice."},
    {id:"Nazrul", label:"Kazi Nazrul Islam", year:1899, school:"Literature", region:"East", subregion:"Bengal", work:"Bidrohi", others:["Agnibina"], note:"Rebel Poet."},
    {id:"Sarat", label:"Sarat Chandra", year:1876, school:"Literature", region:"East", subregion:"Bengal", work:"Devdas", others:["Parineeta"], note:"Novelist."},
    {id:"Madhusudan", label:"Michael Madhusudan", year:1824, school:"Literature", region:"East", subregion:"Bengal", work:"Meghnad Badh", others:["Sharmistha"], note:"Epic Poet."},
    {id:"Ramakrishna", label:"Ramakrishna", year:1836, school:"Bhakti", region:"East", subregion:"Bengal", work:"Kathamrita", others:[], note:"Mystic."},
    {id:"CVRaman", label:"C.V. Raman", year:1888, school:"Science", region:"South", subregion:"Tamil Nadu", work:"Raman Effect", others:[], note:"Physicist."},
    {id:"Bose", label:"J.C. Bose", year:1858, school:"Science", region:"East", subregion:"Bengal", work:"Plant Science", others:[], note:"Physicist/Botanist."},
    {id:"Satyendranath", label:"S.N. Bose", year:1894, school:"Science", region:"East", subregion:"Bengal", work:"Boson", others:["Planck-Bose Statistics"], note:"Physicist."},
    {id:"Gandhi", label:"Mahatma Gandhi", year:1869, school:"Modern", region:"West", subregion:"Gujarat", work:"Experiments with Truth", others:["Hind Swaraj"], note:"Freedom Fighter."},
    {id:"Nivedita", label:"Sister Nivedita", year:1867, school:"Modern", region:"East", subregion:"Bengal", work:"The Master as I Saw Him", others:[], note:"Disciple."},
    
    // --- INDOLOGISTS & HISTORIANS (Full List) ---
    {id:"Megasthenes", label:"Megasthenes", year:-350, school:"Indology", region:"Global", subregion:"Greece", work:"Indica", others:[], note:"Ambassador."},
    {id:"Faxian", label:"Faxian", year:399, school:"Indology", region:"China", subregion:"China", work:"Buddhist Kingdoms", others:[], note:"Pilgrim."},
    {id:"Xuanzang", label:"Xuanzang", year:629, school:"Indology", region:"China", subregion:"China", work:"Great Tang Records", others:[], note:"Pilgrim."},
    {id:"AlBiruni", label:"Al-Biruni", year:973, school:"Indology", region:"Global", subregion:"Persia", work:"Indica", others:["Chronology"], note:"First Indologist."},
    {id:"IbnBattuta", label:"Ibn Battuta", year:1333, school:"Indology", region:"Global", subregion:"Morocco", work:"Rihla", others:[], note:"Traveler."},
    {id:"MarcoPolo", label:"Marco Polo", year:1288, school:"Indology", region:"Global", subregion:"Venice", work:"Travels", others:[], note:"Traveler."},
    {id:"Jones", label:"William Jones", year:1746, school:"Indology", region:"Global", subregion:"UK", work:"Asiatic Researches", others:["Sakuntala Trans"], note:"Indo-European Link."},
    {id:"Wilkins", label:"Charles Wilkins", year:1749, school:"Indology", region:"Global", subregion:"UK", work:"Gita Translation", others:[], note:"Translator."},
    {id:"Prinsep", label:"James Prinsep", year:1799, school:"Indology", region:"Global", subregion:"UK", work:"Decipherment of Brahmi", others:[], note:"Epigraphist."},
    {id:"Cunningham", label:"Alexander Cunningham", year:1814, school:"Indology", region:"Global", subregion:"UK", work:"ASI Reports", others:[], note:"Archaeology."},
    {id:"MaxMuller", label:"Max Müller", year:1823, school:"Indology", region:"Global", subregion:"Germany", work:"Sacred Books", others:["History of Sanskrit Lit"], note:"Philologist."},
    {id:"Weber", label:"Albrecht Weber", year:1825, school:"Indology", region:"Global", subregion:"Germany", work:"Indische Studien", others:[], note:"Vedic Scholar."},
    {id:"MonierWilliams", label:"Monier-Williams", year:1819, school:"Indology", region:"Global", subregion:"UK", work:"Sanskrit Dictionary", others:[], note:"Lexicographer."},
    {id:"Rajendralal", label:"Rajendralal Mitra", year:1822, school:"Indology", region:"East", subregion:"Bengal", work:"Antiquities of Orissa", others:["Indo-Aryans"], note:"First Indian Indologist."},
    {id:"Bhandarkar", label:"R.G. Bhandarkar", year:1837, school:"Indology", region:"West", subregion:"Maharashtra", work:"Vaishnavism/Shaivism", others:[], note:"Historian."},
    {id:"Buhler", label:"Georg Bühler", year:1837, school:"Indology", region:"Global", subregion:"Germany", work:"Encyclopedia", others:[], note:"Manuscripts."},
    {id:"Jacobi", label:"Hermann Jacobi", year:1850, school:"Indology", region:"Global", subregion:"Germany", work:"Jaina Sutras", others:[], note:"Jainism."},
    {id:"Roth", label:"Rudolf Roth", year:1821, school:"Indology", region:"Global", subregion:"Germany", work:"Vedic Philology", others:[], note:"Vedas."},
    {id:"Oldenberg", label:"Hermann Oldenberg", year:1854, school:"Indology", region:"Global", subregion:"Germany", work:"Buddha", others:[], note:"Buddhism."},
    {id:"Renou", label:"Louis Renou", year:1896, school:"Indology", region:"Global", subregion:"France", work:"Vedic India", others:[], note:"Vedas."},
    {id:"Gonda", label:"Jan Gonda", year:1905, school:"Indology", region:"Global", subregion:"Netherlands", work:"Sanskrit Syntax", others:[], note:"Prolific."},
    {id:"Jayaswal", label:"K.P. Jayaswal", year:1881, school:"Indology", region:"East", subregion:"Bihar", work:"Hindu Polity", others:[], note:"Republics."},
    {id:"Raychaudhuri", label:"H.C. Raychaudhuri", year:1892, school:"Indology", region:"East", subregion:"Bengal", work:"Political History", others:[], note:"Ancient India."},
    {id:"Kosambi", label:"D.D. Kosambi", year:1907, school:"Indology", region:"West", subregion:"Goa", work:"Indian History", others:[], note:"Marxist."},
    {id:"Raghavan", label:"V. Raghavan", year:1908, school:"Indology", region:"South", subregion:"Tamil Nadu", work:"Bhoja's Sringara", others:[], note:"Aesthetics."},
    {id:"Basham", label:"A.L. Basham", year:1914, school:"Indology", region:"Global", subregion:"UK", work:"The Wonder That Was India", others:[], note:"Cultural History."},
    {id:"Ingalls", label:"Daniel Ingalls", year:1916, school:"Indology", region:"Global", subregion:"USA", work:"Navya-Nyaya Logic", others:[], note:"Logic."},
    {id:"SitaRamGoel", label:"Sita Ram Goel", year:1921, school:"Indology", region:"North", subregion:"Haryana", work:"Hindu Temples", others:[], note:"Historian."},
    {id:"DharamPal", label:"Dharam Pal", year:1922, school:"Indology", region:"North", subregion:"Punjab", work:"The Beautiful Tree", others:[], note:"Education."},
    {id:"RomilaThapar", label:"Romila Thapar", year:1931, school:"Indology", region:"North", subregion:"Punjab", work:"History of India", others:["Early India"], note:"Ancient History."},
    {id:"IrfanHabib", label:"Irfan Habib", year:1931, school:"Indology", region:"North", subregion:"Aligarh", work:"Agrarian System", others:["Medieval India"], note:"Mughal History."},
    {id:"RSSharma", label:"R.S. Sharma", year:1919, school:"Indology", region:"East", subregion:"Bihar", work:"Indian Feudalism", others:[], note:"Ancient History."},
    {id:"Staal", label:"Frits Staal", year:1930, school:"Indology", region:"Global", subregion:"Netherlands", work:"Agni", others:[], note:"Ritual."},
    {id:"Witzel", label:"Michael Witzel", year:1943, school:"Indology", region:"Global", subregion:"Germany", work:"Vedic Studies", others:[], note:"Vedas."},
    {id:"Doniger", label:"Wendy Doniger", year:1940, school:"Indology", region:"Global", subregion:"USA", work:"The Hindus", others:[], note:"Mythology."},
    {id:"Bronkhorst", label:"Johannes Bronkhorst", year:1946, school:"Indology", region:"Global", subregion:"Netherlands", work:"Greater Magadha", others:[], note:"Cultural."},
    {id:"Sanderson", label:"Alexis Sanderson", year:1948, school:"Indology", region:"Global", subregion:"UK", work:"Shaiva Studies", others:[], note:"Tantra."},
    {id:"Pollock", label:"Sheldon Pollock", year:1948, school:"Indology", region:"Global", subregion:"USA", work:"Language of Gods", others:[], note:"Sanskrit."},
    {id:"Olivelle", label:"Patrick Olivelle", year:1942, school:"Indology", region:"Global", subregion:"Sri Lanka", work:"Upanishads", others:[], note:"Philologist."},
    {id:"Eaton", label:"Richard Eaton", year:1940, school:"Indology", region:"Global", subregion:"USA", work:"Persianate Age", others:[], note:"Islam in India."},
    {id:"Wink", label:"Andre Wink", year:1990, school:"Indology", region:"Global", subregion:"Netherlands", work:"Al-Hind", others:[], note:"Indo-Islamic."},
    {id:"Subrahmanyam", label:"Sanjay Subrahmanyam", year:1961, school:"Indology", region:"South", subregion:"Tamil Nadu", work:"Connected History", others:[], note:"Early Modern."},
    {id:"Shulman", label:"David Shulman", year:1949, school:"Indology", region:"Global", subregion:"Israel", work:"Temple Myths", others:[], note:"South India."},
    {id:"Hart", label:"George Hart", year:1945, school:"Indology", region:"Global", subregion:"USA", work:"Tamil Poems", others:[], note:"Sangam."},
    {id:"Jamison", label:"Stephanie Jamison", year:2000, school:"Indology", region:"Global", subregion:"USA", work:"Rig Veda Trans", others:[], note:"Vedas."},
    {id:"Brereton", label:"Joel Brereton", year:2000, school:"Indology", region:"Global", subregion:"USA", work:"Rig Veda Trans", others:[], note:"Vedas."},
    {id:"Voltaire", label:"Voltaire", year:1694, school:"Indology", region:"Global", subregion:"France", work:"Essai", others:[], note:"Indophile."},
    {id:"Schopenhauer", label:"Schopenhauer", year:1788, school:"Indology", region:"Global", subregion:"Germany", work:"World as Will", others:[], note:"Upanishads admirer."},
    {id:"Tesla", label:"Tesla", year:1856, school:"Indology", region:"Global", subregion:"USA", work:"AC", others:[], note:"Vedantic Physics."},
    {id:"Eliot", label:"T.S. Eliot", year:1888, school:"Indology", region:"Global", subregion:"UK", work:"Waste Land", others:[], note:"Sanskrit influence."},
    {id:"Oppenheimer", label:"Oppenheimer", year:1904, school:"Indology", region:"Global", subregion:"USA", work:"Trinity", others:[], note:"Gita Scholar."},
    {id:"Harrison", label:"Harrison", year:1943, school:"Indology", region:"Global", subregion:"UK", work:"Sitar", others:[], note:"Beatles."},
    {id:"Goethe", label:"Goethe", year:1749, school:"Indology", region:"Global", subregion:"Germany", note:"Admired Shakuntalam", others:[]},
    {id:"Thoreau", label:"Thoreau", year:1817, school:"Indology", region:"Global", subregion:"USA", work:"Walden", others:[], note:"Transcendentalist."},
    {id:"Emerson", label:"Emerson", year:1803, school:"Indology", region:"Global", subregion:"USA", work:"Brahma", others:[], note:"Transcendentalist."},
    {id:"Zimmer", label:"Heinrich Zimmer", year:1890, school:"Indology", region:"Global", subregion:"Germany", work:"Philosophies of India", others:[], note:"Mythology."},
    {id:"Deussen", label:"Paul Deussen", year:1845, school:"Indology", region:"Global", subregion:"Germany", work:"Sixty Upanishads", others:[], note:"Vedanta."}
];

// --- 2. LINEAGES (The Connections) ---
const lineages = [
    {s:"Narayana", t:"Brahma", type:"Guru"}, {s:"Brahma", t:"Vashishta", type:"Guru"},
    {s:"Vashishta", t:"Shakti", type:"Guru"}, {s:"Shakti", t:"Parashara", type:"Guru"},
    {s:"Parashara", t:"Vyasa", type:"Guru"}, {s:"Vyasa", t:"Shuka", type:"Guru"},
    {s:"Shiva", t:"Vasugupta", type:"Divine"}, {s:"Shiva", t:"Shankara", type:"Divine"},
    {s:"Shuka", t:"Gaudapada", type:"Lineage"}, {s:"Gaudapada", t:"Govinda", type:"Guru"},
    {s:"Govinda", t:"Shankara", type:"Guru"}, {s:"Shankara", t:"Suresvara", type:"Guru"},
    {s:"Shankara", t:"Padmapada", type:"Guru"}, {s:"Shankara", t:"Totaka", type:"Guru"},
    {s:"Shankara", t:"Hastamalaka", type:"Guru"}, {s:"Shankara", t:"Vacaspati", type:"Influence"},
    {s:"Shankara", t:"Vidyaranya", type:"Lineage"}, {s:"Shankara", t:"Madhusudana", type:"Lineage"},
    {s:"Shankara", t:"Vivekananda", type:"Lineage"},
    {s:"Narayana", t:"Madhva", type:"Divine"}, {s:"Madhva", t:"Padmanabha", type:"Guru"}, 
    {s:"Padmanabha", t:"Narahari", type:"Guru"}, {s:"Madhva", t:"Jayatirtha", type:"Lineage"}, 
    {s:"Jayatirtha", t:"Vyasatirtha", type:"Lineage"}, {s:"Vyasatirtha", t:"Raghavendra", type:"Lineage"},
    {s:"Narayana", t:"Nammalvar", type:"Inspiration"}, {s:"Nammalvar", t:"Nathamuni", type:"Inspiration"},
    {s:"Nathamuni", t:"Yamuna", type:"GrandGuru"}, {s:"Yamuna", t:"Ramanuja", type:"Preceptor"},
    {s:"Ramanuja", t:"Desika", type:"Lineage"}, {s:"Ramanuja", t:"Pillai", type:"Lineage"},
    {s:"Vasugupta", t:"Somananda", type:"Lineage"}, {s:"Somananda", t:"Utpaladeva", type:"Guru"},
    {s:"Utpaladeva", t:"Abhinavagupta", type:"GrandGuru"}, {s:"Abhinavagupta", t:"Kshemaraja", type:"Guru"},
    {s:"Abhinavagupta", t:"Lakshmanjoo", type:"Lineage"},
    {s:"Gautama", t:"Vatsyayana", type:"Lineage"}, {s:"Udayana", t:"Gangesa", type:"Influence"},
    {s:"Gangesa", t:"Raghunatha", type:"Lineage"}, {s:"Raghunatha", t:"Gadadhara", type:"Lineage"},
    {s:"Buddha", t:"Mahakassapa", type:"Guru"}, {s:"Mahakassapa", t:"Ananda", type:"Guru"},
    {s:"Buddha", t:"Nagarjuna", type:"Inspiration"}, {s:"Nagarjuna", t:"Aryadeva", type:"Guru"},
    {s:"Asanga", t:"Vasubandhu", type:"Brother"}, {s:"Vasubandhu", t:"Dignaga", type:"Lineage"},
    {s:"Bodhidharma", t:"Huineng", type:"Lineage"}, {s:"Padmasambhava", t:"Milarepa", type:"Lineage"},
    {s:"Tsongkhapa", t:"DalaiLama", type:"Lineage"},
    {s:"Mahavira", t:"GautamaGanadhara", type:"Guru"}, {s:"Mahavira", t:"Bhadrabahu", type:"Lineage"},
    {s:"Bhadrabahu", t:"Kundakunda", type:"Lineage"}, {s:"Mahavira", t:"Hemachandra", type:"Lineage"},
    {s:"Jaimini", t:"Shabara", type:"Lineage"}, {s:"Shabara", t:"Kumarila", type:"Lineage"},
    {s:"Kumarila", t:"Mandana", type:"Guru"}, {s:"Kumarila", t:"Prabhakara", type:"Guru"},
    {s:"Kapila", t:"Asuri", type:"Guru"}, {s:"Asuri", t:"Panchashikha", type:"Guru"},
    {s:"Panchashikha", t:"IshvaraKrishna", type:"Lineage"},
    {s:"Ramanuja", t:"Madhva", type:"Reaction"}, {s:"Jayadeva", t:"Chaitanya", type:"Influence"},
    {s:"Chaitanya", t:"Tagore", type:"Influence"}, {s:"Ramakrishna", t:"Vivekananda", type:"Guru"},
    {s:"Vivekananda", t:"Nivedita", type:"Guru"},
    {s:"Panini", t:"Voltaire", type:"Study"}, {s:"Vyasa", t:"Oppenheimer", type:"Study"},
    {s:"Yajnavalkya", t:"Schopenhauer", type:"Study"}, {s:"Vivekananda", t:"Tesla", type:"Meeting"},
    {s:"Kalidasa", t:"Goethe", type:"Inspiration"}, {s:"Jones", t:"MaxMuller", type:"Influence"}
];